-- Migration 018: Seed All 67 Florida Counties with Agencies
-- Description: Pre-configure all Florida counties with 1:1 agency mapping
-- Date: 2025-12-01
-- Source: Official Florida county list (67 counties as of 1925)

-- First, create agencies for each county (1:1 mapping)
INSERT INTO agencies (id, name, created_at) VALUES
(gen_random_uuid(), 'Alachua County HVAC Agency', NOW()),
(gen_random_uuid(), 'Baker County HVAC Agency', NOW()),
(gen_random_uuid(), 'Bay County HVAC Agency', NOW()),
(gen_random_uuid(), 'Bradford County HVAC Agency', NOW()),
(gen_random_uuid(), 'Brevard County HVAC Agency', NOW()),
(gen_random_uuid(), 'Broward County HVAC Agency', NOW()),
(gen_random_uuid(), 'Calhoun County HVAC Agency', NOW()),
(gen_random_uuid(), 'Charlotte County HVAC Agency', NOW()),
(gen_random_uuid(), 'Citrus County HVAC Agency', NOW()),
(gen_random_uuid(), 'Clay County HVAC Agency', NOW()),
(gen_random_uuid(), 'Collier County HVAC Agency', NOW()),
(gen_random_uuid(), 'Columbia County HVAC Agency', NOW()),
(gen_random_uuid(), 'DeSoto County HVAC Agency', NOW()),
(gen_random_uuid(), 'Dixie County HVAC Agency', NOW()),
(gen_random_uuid(), 'Duval County HVAC Agency', NOW()),
(gen_random_uuid(), 'Escambia County HVAC Agency', NOW()),
(gen_random_uuid(), 'Flagler County HVAC Agency', NOW()),
(gen_random_uuid(), 'Franklin County HVAC Agency', NOW()),
(gen_random_uuid(), 'Gadsden County HVAC Agency', NOW()),
(gen_random_uuid(), 'Gilchrist County HVAC Agency', NOW()),
(gen_random_uuid(), 'Glades County HVAC Agency', NOW()),
(gen_random_uuid(), 'Gulf County HVAC Agency', NOW()),
(gen_random_uuid(), 'Hamilton County HVAC Agency', NOW()),
(gen_random_uuid(), 'Hardee County HVAC Agency', NOW()),
(gen_random_uuid(), 'Hendry County HVAC Agency', NOW()),
(gen_random_uuid(), 'Hernando County HVAC Agency', NOW()),
(gen_random_uuid(), 'Highlands County HVAC Agency', NOW()),
(gen_random_uuid(), 'Hillsborough County HVAC Agency', NOW()),
(gen_random_uuid(), 'Holmes County HVAC Agency', NOW()),
(gen_random_uuid(), 'Indian River County HVAC Agency', NOW()),
(gen_random_uuid(), 'Jackson County HVAC Agency', NOW()),
(gen_random_uuid(), 'Jefferson County HVAC Agency', NOW()),
(gen_random_uuid(), 'Lafayette County HVAC Agency', NOW()),
(gen_random_uuid(), 'Lake County HVAC Agency', NOW()),
(gen_random_uuid(), 'Lee County HVAC Agency', NOW()),
(gen_random_uuid(), 'Leon County HVAC Agency', NOW()),
(gen_random_uuid(), 'Levy County HVAC Agency', NOW()),
(gen_random_uuid(), 'Liberty County HVAC Agency', NOW()),
(gen_random_uuid(), 'Madison County HVAC Agency', NOW()),
(gen_random_uuid(), 'Manatee County HVAC Agency', NOW()),
(gen_random_uuid(), 'Marion County HVAC Agency', NOW()),
(gen_random_uuid(), 'Martin County HVAC Agency', NOW()),
(gen_random_uuid(), 'Miami-Dade County HVAC Agency', NOW()),
(gen_random_uuid(), 'Monroe County HVAC Agency', NOW()),
(gen_random_uuid(), 'Nassau County HVAC Agency', NOW()),
(gen_random_uuid(), 'Okaloosa County HVAC Agency', NOW()),
(gen_random_uuid(), 'Okeechobee County HVAC Agency', NOW()),
(gen_random_uuid(), 'Orange County HVAC Agency', NOW()),
(gen_random_uuid(), 'Osceola County HVAC Agency', NOW()),
(gen_random_uuid(), 'Palm Beach County HVAC Agency', NOW()),
(gen_random_uuid(), 'Pasco County HVAC Agency', NOW()),
(gen_random_uuid(), 'Pinellas County HVAC Agency', NOW()),
(gen_random_uuid(), 'Polk County HVAC Agency', NOW()),
(gen_random_uuid(), 'Putnam County HVAC Agency', NOW()),
(gen_random_uuid(), 'St. Johns County HVAC Agency', NOW()),
(gen_random_uuid(), 'St. Lucie County HVAC Agency', NOW()),
(gen_random_uuid(), 'Santa Rosa County HVAC Agency', NOW()),
(gen_random_uuid(), 'Sarasota County HVAC Agency', NOW()),
(gen_random_uuid(), 'Seminole County HVAC Agency', NOW()),
(gen_random_uuid(), 'Sumter County HVAC Agency', NOW()),
(gen_random_uuid(), 'Suwannee County HVAC Agency', NOW()),
(gen_random_uuid(), 'Taylor County HVAC Agency', NOW()),
(gen_random_uuid(), 'Union County HVAC Agency', NOW()),
(gen_random_uuid(), 'Volusia County HVAC Agency', NOW()),
(gen_random_uuid(), 'Wakulla County HVAC Agency', NOW()),
(gen_random_uuid(), 'Walton County HVAC Agency', NOW()),
(gen_random_uuid(), 'Washington County HVAC Agency', NOW());

-- Then, create counties linked to their agencies
-- Start with platform='Unknown' for automated detection
-- Exception: Hillsborough County (known Accela with code HCFL)
INSERT INTO counties (
    id,
    agency_id,
    name,
    state,
    state_full_name,
    county_code,
    status,
    platform,
    platform_confidence,
    is_active,
    created_at
) VALUES
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Alachua County HVAC Agency'), 'Alachua County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Baker County HVAC Agency'), 'Baker County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Bay County HVAC Agency'), 'Bay County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Bradford County HVAC Agency'), 'Bradford County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Brevard County HVAC Agency'), 'Brevard County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Broward County HVAC Agency'), 'Broward County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Calhoun County HVAC Agency'), 'Calhoun County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Charlotte County HVAC Agency'), 'Charlotte County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Citrus County HVAC Agency'), 'Citrus County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Clay County HVAC Agency'), 'Clay County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Collier County HVAC Agency'), 'Collier County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Columbia County HVAC Agency'), 'Columbia County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'DeSoto County HVAC Agency'), 'DeSoto County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Dixie County HVAC Agency'), 'Dixie County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Duval County HVAC Agency'), 'Duval County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Escambia County HVAC Agency'), 'Escambia County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Flagler County HVAC Agency'), 'Flagler County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Franklin County HVAC Agency'), 'Franklin County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Gadsden County HVAC Agency'), 'Gadsden County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Gilchrist County HVAC Agency'), 'Gilchrist County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Glades County HVAC Agency'), 'Glades County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Gulf County HVAC Agency'), 'Gulf County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Hamilton County HVAC Agency'), 'Hamilton County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Hardee County HVAC Agency'), 'Hardee County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Hendry County HVAC Agency'), 'Hendry County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Hernando County HVAC Agency'), 'Hernando County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Highlands County HVAC Agency'), 'Highlands County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
-- Hillsborough County: Known Accela county with code HCFL
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Hillsborough County HVAC Agency'), 'Hillsborough County', 'FL', 'Florida', 'HCFL', 'not_configured', 'Accela', 'Confirmed', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Holmes County HVAC Agency'), 'Holmes County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Indian River County HVAC Agency'), 'Indian River County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Jackson County HVAC Agency'), 'Jackson County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Jefferson County HVAC Agency'), 'Jefferson County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Lafayette County HVAC Agency'), 'Lafayette County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Lake County HVAC Agency'), 'Lake County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Lee County HVAC Agency'), 'Lee County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Leon County HVAC Agency'), 'Leon County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Levy County HVAC Agency'), 'Levy County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Liberty County HVAC Agency'), 'Liberty County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Madison County HVAC Agency'), 'Madison County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Manatee County HVAC Agency'), 'Manatee County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Marion County HVAC Agency'), 'Marion County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Martin County HVAC Agency'), 'Martin County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Miami-Dade County HVAC Agency'), 'Miami-Dade County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Monroe County HVAC Agency'), 'Monroe County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Nassau County HVAC Agency'), 'Nassau County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Okaloosa County HVAC Agency'), 'Okaloosa County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Okeechobee County HVAC Agency'), 'Okeechobee County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Orange County HVAC Agency'), 'Orange County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Osceola County HVAC Agency'), 'Osceola County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Palm Beach County HVAC Agency'), 'Palm Beach County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Pasco County HVAC Agency'), 'Pasco County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Pinellas County HVAC Agency'), 'Pinellas County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Polk County HVAC Agency'), 'Polk County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Putnam County HVAC Agency'), 'Putnam County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'St. Johns County HVAC Agency'), 'St. Johns County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'St. Lucie County HVAC Agency'), 'St. Lucie County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Santa Rosa County HVAC Agency'), 'Santa Rosa County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Sarasota County HVAC Agency'), 'Sarasota County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Seminole County HVAC Agency'), 'Seminole County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Sumter County HVAC Agency'), 'Sumter County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Suwannee County HVAC Agency'), 'Suwannee County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Taylor County HVAC Agency'), 'Taylor County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Union County HVAC Agency'), 'Union County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Volusia County HVAC Agency'), 'Volusia County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Wakulla County HVAC Agency'), 'Wakulla County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Walton County HVAC Agency'), 'Walton County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW()),
(gen_random_uuid(), (SELECT id FROM agencies WHERE name = 'Washington County HVAC Agency'), 'Washington County', 'FL', 'Florida', NULL, 'not_configured', 'Unknown', 'Unknown', true, NOW());
